# Generated by Django 3.0.7 on 2020-06-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('sobre_nome', models.CharField(max_length=20, verbose_name='Sobre Nome')),
                ('senha', models.CharField(max_length=10, verbose_name='Senha')),
                ('receita', models.FloatField(verbose_name='Receita')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
