# Generated by Django 3.0.7 on 2020-06-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
