# Generated by Django 3.0.7 on 2020-06-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria',
            new_name='categorias',
        ),
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuarios',
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
