# Generated by Django 3.0.7 on 2020-06-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_auto_20200608_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.categorias', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orcamento.usuarios', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'despesas',
            },
        ),
    ]
